# Generated by Django 2.2.7 on 2019-11-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maned',
            new_name='Month',
        ),
    ]
