# Generated by Django 2.2.7 on 2019-11-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0002_auto_20191112_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunde', models.CharField(max_length=255)),
                ('kundeinformasjon', models.CharField(max_length=255)),
                ('badresse', models.CharField(max_length=255)),
                ('bpostnr', models.PositiveSmallIntegerField()),
                ('bpoststed', models.CharField(max_length=255)),
                ('fadresse', models.CharField(max_length=255)),
                ('fpostnr', models.PositiveSmallIntegerField()),
                ('fpoststed', models.CharField(max_length=255)),
                ('kontaktperson', models.CharField(max_length=255)),
                ('tlf1', models.PositiveIntegerField()),
                ('tlf2', models.PositiveIntegerField()),
                ('nummer', models.PositiveIntegerField()),
                ('tripletex', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=255)),
                ('kommentar', models.TextField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontroll.Month')),
            ],
        ),
    ]
