# Generated by Django 2.2.7 on 2019-11-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
