# Generated by Django 2.2.7 on 2019-11-12 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0005_auto_20191112_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='kontroll.Month'),
        ),
    ]
