# Generated by Django 2.2.7 on 2019-11-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0006_auto_20191112_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slokkemiddel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
            ],
        ),
    ]
