# Generated by Django 2.2.7 on 2019-11-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0007_slokkemiddel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slokkemiddel',
            new_name='Extinguishant',
        ),
    ]
