# Generated by Django 2.2.7 on 2019-11-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0008_auto_20191116_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extinguishant',
            old_name='navn',
            new_name='type',
        ),
    ]
