# Generated by Django 2.2.7 on 2019-11-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0009_auto_20191116_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extinguishant',
            old_name='type',
            new_name='navn',
        ),
        migrations.AlterField(
            model_name='customer',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontroll.Month'),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabrikat', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('lengde', models.CharField(max_length=255)),
                ('handslokker', models.BooleanField(default=False)),
                ('brannpost', models.BooleanField(default=False)),
                ('slangevogn', models.BooleanField(default=False)),
                ('extinguishant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontroll.Extinguishant')),
            ],
        ),
    ]
