# Generated by Django 2.2.7 on 2019-11-16 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0010_auto_20191116_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='lengde',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refnr', models.PositiveSmallIntegerField()),
                ('lokasjon', models.CharField(blank=True, max_length=255, null=True)),
                ('etg', models.CharField(blank=True, max_length=255, null=True)),
                ('plassering', models.CharField(blank=True, max_length=255, null=True)),
                ('sisteservice', models.PositiveSmallIntegerField()),
                ('sistekontroll', models.PositiveSmallIntegerField()),
                ('nesteservice', models.PositiveSmallIntegerField()),
                ('nestekontroll', models.PositiveSmallIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontroll.Customer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontroll.Type')),
            ],
        ),
    ]
