# Generated by Django 2.2.7 on 2019-11-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0011_auto_20191116_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='type',
        ),
        migrations.AddField(
            model_name='extinguishant',
            name='brannpost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extinguishant',
            name='fabrikat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extinguishant',
            name='handslokker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extinguishant',
            name='lengde',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extinguishant',
            name='slangevogn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extinguishant',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='extinguishant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kontroll.Extinguishant'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
