# Generated by Django 2.2.7 on 2019-11-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0013_auto_20191116_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='prodyear',
            field=models.PositiveSmallIntegerField(blank=True, default=2010),
        ),
        migrations.AlterField(
            model_name='object',
            name='nestekontroll',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='nesteservice',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='sistekontroll',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='sisteservice',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
