# Generated by Django 2.2.7 on 2019-11-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0014_auto_20191117_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrolldato', models.DateField(blank=True, null=True)),
                ('servicedato', models.DateField(blank=True, null=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontroll.Object')),
            ],
        ),
    ]
