# Generated by Django 2.2.7 on 2019-11-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0015_objtr'),
    ]

    operations = [
        migrations.AddField(
            model_name='objtr',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kontroll.Customer'),
            preserve_default=False,
        ),
    ]
