# Generated by Django 2.2.7 on 2019-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0016_objtr_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slokketype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='extinguishant',
            name='brannpost',
        ),
        migrations.RemoveField(
            model_name='extinguishant',
            name='handslokker',
        ),
        migrations.RemoveField(
            model_name='extinguishant',
            name='slangevogn',
        ),
    ]
