# Generated by Django 2.2.7 on 2019-11-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0018_extinguishant_slokketype'),
    ]

    operations = [
        migrations.AddField(
            model_name='objtr',
            name='avvik',
            field=models.BooleanField(default=False),
        ),
    ]
