# Generated by Django 2.2.7 on 2019-12-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0019_objtr_avvik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='refnr',
        ),
        migrations.CreateModel(
            name='Avvik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avvik', models.TextField()),
                ('slokketype', models.ManyToManyField(to='kontroll.Slokketype')),
            ],
        ),
    ]
