# Generated by Django 2.2.7 on 2019-12-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0020_auto_20191204_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='object',
            name='avvik',
            field=models.BooleanField(default=False),
        ),
    ]
