# Generated by Django 2.2.7 on 2019-12-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0021_auto_20191204_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='sisteservice',
        ),
    ]
