# Generated by Django 2.2.7 on 2019-12-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0022_remove_object_sisteservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='sisteservice',
            field=models.DateField(blank=True, null=True),
        ),
    ]
