# Generated by Django 2.2.7 on 2019-12-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0023_object_sisteservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='nestekontroll',
        ),
        migrations.RemoveField(
            model_name='object',
            name='nesteservice',
        ),
        migrations.RemoveField(
            model_name='object',
            name='sistekontroll',
        ),
    ]
