# Generated by Django 2.2.7 on 2019-12-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0027_auto_20191210_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='nesteservice',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='prodyear',
            field=models.PositiveSmallIntegerField(blank=True, default=2010),
        ),
    ]
