# Generated by Django 2.2.7 on 2019-12-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0029_month_intervall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='intervall',
        ),
        migrations.AddField(
            model_name='slokketype',
            name='intervall',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
