# Generated by Django 2.2.7 on 2019-12-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0030_auto_20191210_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='etg',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='lokasjon',
            field=models.CharField(default='lokasjon', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='plassering',
            field=models.CharField(default='plassering', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='prodyear',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
