# Generated by Django 2.2.7 on 2019-12-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0031_auto_20191211_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='etg',
            field=models.SmallIntegerField(),
        ),
    ]
