# Generated by Django 2.2.7 on 2019-12-28 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0032_auto_20191212_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objtr',
            name='avvik',
        ),
        migrations.AddField(
            model_name='objtr',
            name='avvik',
            field=models.ManyToManyField(blank=True, to='kontroll.Avvik'),
        ),
        migrations.CreateModel(
            name='AvvikTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontroll.Object')),
            ],
        ),
    ]
