# Generated by Django 2.2.7 on 2019-12-28 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0033_auto_20191228_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvvikTr',
        ),
    ]
