# Generated by Django 2.2.7 on 2020-01-04 21:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0035_auto_20200104_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 21, 54, 34, 982643, tzinfo=utc),
                                       editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 21, 54, 56, 92940, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
