# Generated by Django 2.2.7 on 2020-01-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0038_auto_20200105_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='objtr',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
