# Generated by Django 2.2.7 on 2020-01-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0039_objtr_kommentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avviktr',
            name='customer',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='kontroll.Customer'),
            preserve_default=False,
        ),
    ]
