# Generated by Django 2.2.7 on 2020-01-06 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0041_objtr_utbedret_avvik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvvikTr',
        ),
    ]
