# Generated by Django 2.2.7 on 2020-01-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0042_delete_avviktr'),
    ]

    operations = [
        migrations.AddField(
            model_name='objtr',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objtr',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
