# Generated by Django 2.2.7 on 2020-01-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0043_auto_20200119_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='objtr',
            name='user',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
