# Generated by Django 2.2.7 on 2020-01-29 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kontroll', '0045_auto_20200124_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='status',
        ),
    ]
