# Generated by Django 3.1.6 on 2021-03-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0046_remove_object_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beskrivelse', models.CharField(max_length=255)),
            ],
        ),
    ]
