# Generated by Django 3.1.6 on 2021-03-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontroll', '0047_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='objtr',
            name='extra_antall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objtr',
            name='extra_beskrivelse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_beskrivelse_extra', to='kontroll.extra'),
        ),
        migrations.AddField(
            model_name='objtr',
            name='extra_kommentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objtr',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kontroll.object'),
        ),
    ]
